name: GraphCDN
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Build schema
        run: yarn install && cd packages/api && yarn buildSchema
      - name: Push schema
        run: npx graphcdn push schema
        env:
          GRAPHCDN_TOKEN: ${{ secrets.GRAPHCDN_TOKEN }}