name: Deploy

on:
  push:
    branches:
      - main

jobs:
  # # JOB to run change detection
  # changes:
  #   runs-on: ubuntu-latest
  #   # Set job outputs to values from filter step
  #   outputs:
  #     api: ${{ steps.filter.outputs.api }}

  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v2

  #     - uses: dorny/paths-filter@v2
  #       id: filter
  #       with:
  #         filters: |
  #           api:
  #             - 'packages/api/**'

  build:
    # needs: changes
    # if: needs.steps.filter.outputs.api == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nq-boilerplate"
          heroku_email: "info@noquarter.co"
